### ISSUE TITLE
support firefox

### ISSUE THREAD

**Issue by edrex** [pvh/eleanor#4]
I'm 100% firefox these days (try it, you'll like it!).

I'll work on getting this running as a webextension under firefox.

First test shows a few warnings to fix: https://clbin.com/a7mT1.

pressing the extension button on a site gives:

```
error during executeScript background.js:1:3951
Unchecked lastError value: Error: Attempt to postMessage on disconnected port
```
Next steps:
- [ ] Investigate manifest.json warnings (compare to other cross-browser clip extensions)
  - https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Browser_compatibility_for_manifest.json
- [ ] debug page + selection clip functions

**Comment by pvh** [comment]
I suspect the issue is something to do with the binary protocol. I know the project I based our implementation on had firefox support too, but I didn't bother to implement it at the time since nobody on the team was using firefox then. Happy to take a PR though!

**Comment by edrex** [comment]
Need to copy a "native manifest" for firefox (+set registry key on windows) in [pushpin/ClipperHost.ts](https://github.com/automerge/pushpin/blob/master/src/ClipperHost.ts). I tested with a manually copied one and page clipping works.

**Comment by edrex** [comment]
I need to focus on other priorities (and realized my clipboard works fine) so I think I'll close this, and if at some point somebody wants to put in the effort to extend the host install script for FF can reopen.

**Comment by edrex** [comment]
@pvh wdyt about using the setup module in https://www.npmjs.com/package/web-ext-native-msg ?

**Comment by pvh** [comment]
Seems reasonable -- if you send a PR, I can test Firefox & Chrome on Windows.
